# docker-compose.yaml  (hyphen between docker‑compose)
version: "3.9"

services:
  lrs_pair_engine:
    build: .
    image: kryptbot:latest          # reuse the same layer‑cached image
    command: python -m bot.engines.fvg_orderflow_pair_engine
    container_name: krypt_pair
    env_file: .env
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - .:/app                      # mount the current directory to /app in the container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
